spring:
    thymeleaf3:
        decoupled-logic: true
    datasource:
        url: jdbc:mysql://localhost:3306/miniproject?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: root
        password: rnjs!@2804
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        defer-datasource-initialization: true
        open-in-view: true
        hibernate.ddl-auto: update
        show-sql: true
        properties:
            hibernate.format_sql: true
            hibernate.default_batch_fetch_size: 100
        generate-ddl: true

    sql:
        init:
            mode: always